CCOMPILER = gcc
CXXCOMPILER = g++
FLAGS = -Wall
EXPORTFOLDER = export

main:
	cmake -DCMAKE_C_COMPILER=$(CCOMPILER) -DCMAKE_CXX_COMPILER=$(CXXCOMPILER) -B $(EXPORTFOLDER) -G Ninja $(FLAGS)
	ninja -C $(EXPORTFOLDER)
